args:
  image2video: False
  latent_channels: 16
  mode: inference
  load: /DATA/jupyter/personal/zhipu/cogvideox_bilibili/pretrained_model/ft
  batch_size: 1
  input_type: txt
  input_file: /DATA/jupyter/personal/zhipu/cogvideox_bilibili/prompt/testcase.txt
  sampling_imagse_size: [480, 720]
  sampling_num_frames: 13
  sampling_fps: 8
  bf16: True
  output_dir: samples/test0725_2b_2


#  load: /workspace/ckpt/tjy/sat_sdxl/ckpts/ft-480-5b-07-02-20-54